package day4.Objects.InfoCar;

	public enum CarColor {
		DARK_BROWN, PURPLE, CYAN, BRIGHT_VIOLET, 
		SCARLE, DENIM, ULTRAMARINE, TURQUOISE, 
		AMETHYST, VIOLET, CRIMSON, DARK_SLATE_GRAY, 
		MAGENTA, MAUVE, AMARANTH, PALE_CHESTNUT, PASTEL_PINK;

	}

	
